# Site settings
title: "Tom Diggle"
email: "tom@tomdiggle.com"
description: "iOS and front end web developer."
baseurl: ""
url: "http://tomdiggle.com"
vanityurl: "http://diggle.co"
rssfeed: "http://tomdiggle.com/feed"
available_for_work: false

# Build settings
production: false
markdown: kramdown
permalink: /:title/
source: source
destination: public
layouts_dir: ./_tomdiggle
paginate: 6
paginate_path: "/page/:num"

gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap

# Generate categories
category_dir: /categories

assets:
  sources:
    - _assets/stylesheets
    - _assets/images
    - _assets/javascripts
    - _assets/fonts
    - _assets/posts

  features:
    automatic_img_size: false

# Twitter
twitter_user: tomdiggle
twitter_tweet_button: true
