# Site settings
title: Tom Diggle
email: tom@tomdiggle.com
description: Freelance web developer with a passion for iOS
logo: /assets/tomdiggle-logo.png
author:
    site: Tom Diggle
    twitter: tomdiggle
baseurl: ""
url: http://tomdiggle.com
vanity_url: http://diggle.co
rssfeed: /feed
available_for_work: false
twitter:
    username: tomdiggle
social:
    links:
        - https://twitter.com/tomdiggle
        - https://github.com/tomdiggle

# Build settings
markdown: kramdown
permalink: /:title/
source: source
destination: public
layouts_dir: ./_tomdiggle
paginate: 6
paginate_path: /page/:num

# Gems
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Generate categories
category_dir: /categories

# Jekyll Assets
assets:
  digest: false

  sources:
    - _assets/stylesheets
    - _assets/images
    - _assets/javascripts
    - _assets/fonts
    - _assets/posts

  features:
    automatic_img_size: false
