# Site settings
title: Tom Diggle
email: tom@tomdiggle.com
description: "Write an awesome description for your new site here."
baseurl: ""
url: "http://tomdiggle.com"
rssfeed: "http://tomdiggle.com/feed"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
source: source
destination: public
layouts: ./_tomdiggle

gems:
  - jekyll-sitemap

assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/posts
#  css_compressor: sass
  cache: false
  